# Generated by Django 4.1.1 on 2022-10-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NEWAPP', '0002_place2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place2',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
